Remove hard-coded `jsxFactory`
React now supports [fragments](https://reactjs.org/docs/fragments.html#short-syntax) to enable components to return lists of elements without an explicit container.

```ts
<>
  <li>First</li>
  <li>Second</li>
</>
```

Unfortunately, TypeScript's support for this syntax breaks when `jsxFactory` is explicitly set:

```
error TS17016: JSX fragment is not supported when using --jsxFactory
```

Since TypeScript sets the same default for `jsxFactory` that the Bazel rule did, we can remove the hardcoded Bazel flag and let TypeScript do the right thing.